### PR TITLE
Move to Project Scaffold + .Net 35 support

### PR DESCRIPTION
**Pull request by varon**
This PR does the above. You can build it using ./build.cmd or ./build.sh

You might need to make some changes to get this working on your CI server.

### CODE REVIEW

**Comment by varon** [comment]
The tests seem to all pass on my side. It's probably a configuration issue:
```
Starting Target: RunTests (==> CopyBinaries)
C:\Work\github\aether\packages\NUnit.Runners\tools\nunit-console.exe "-nologo" "-noshadow" "-labels" "C:\Work\github\aet
her\tests\Aether.Tests\bin\Release\Aether.Tests.dll" "-xml:TestResults.xml"
C:\Work\github\aether\packages\NUnit.Runners\tools\nunit-console.exe "-nologo" "-noshadow" "-labels" "C:\Work\github\aet
her\tests\Aether.Tests\bin\Release\Aether.Tests.dll" "-xml:TestResults.xml"
ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
***** Aether.Tests.Composition.isomorphism over partial return None when None
***** Aether.Tests.Composition.isomorphism over partial return value when Some
***** Aether.Tests.Composition.isomorphism over partial sets value when None
***** Aether.Tests.Composition.isomorphism over partial sets value when Some
***** Aether.Tests.Composition.multiple isomorphisms over partial return None when None
***** Aether.Tests.Composition.multiple isomorphisms over partial return value when Some
***** Aether.Tests.Composition.multiple isomorphisms over partial sets value when None
***** Aether.Tests.Composition.multiple isomorphisms over partial sets value when Some
***** Aether.Tests.Functions.Lens.get returns correct values
***** Aether.Tests.Functions.Lens.getPartial returns correct values
***** Aether.Tests.Functions.Lens.map modifies values correctly
***** Aether.Tests.Functions.Lens.mapPartial modifies values correctly
***** Aether.Tests.Functions.Lens.set sets value correctly
***** Aether.Tests.Functions.Lens.setPartial sets value correctly

Tests run: 14, Errors: 0, Failures: 0, Inconclusive: 0, Time: 0.305643749781216 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

Finished Target: RunTests

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Clean          00:00:00.0061609
AssemblyInfo   00:00:00.0104359
Build          00:00:00.4058076
Build-NET40    00:00:00.2471806
Build-NET35    00:00:00.2393580
CopyBinaries   00:00:00.0142938
RunTests       00:00:01.5252672
Total:         00:00:02.4732217
Status:        Ok
---------------------------------------------------------------------
```

**Comment by kolektiv** [comment]
Yeah, it looks like some kind of assembly binding problem, I'm not too
sure! I can try and take a look over the weekend if I get some spare
minutes!

**Comment by varon** [comment]
@kolektiv Did you have manage to take a look at this yet?

**Comment by kolektiv** [comment]
I haven't had a chance to look I'm afraid, struggling to find many spare days for a week or so! Are you able to repro the problem elsewhere at all?

**Comment by varon** [comment]
Apologies for not getting back to you here. I'm not able to reproduce the error from my side. A clean build produces valid output as I provided above.

Are you able to do so on your local machine, or is it an Appveyor specific problem?

**Comment by varon** [comment]
@kolektiv Any luck?

**Comment by kolektiv** [comment]
Sorry, I'm travelling this week but I'll work this out and merge it when I get back, one way or another!

**Comment by varon** [comment]
Thanks for the update! I look forward to it.

**Comment by varon** [comment]
@kolektiv A gentle reminder that we're still waiting for this to get merged in. Hope the holiday was good.

**Comment by varon** [comment]
@kolektiv I'm still waiting for your feedback. It's been over a month now, so please spend a few minutes to either merge or tell me what to fix here.

**Comment by kolektiv** [comment]
I'll take a look at this today and get something merged. Sorry, have had a few things going on outside of code for a few weeks, sadly!

**Comment by varon** [comment]
@kolektiv,

I understand that your schedule has been busy, but it's time to face the facts on this PR.

I've been more than polite, accommodating and reasonable in dealing with your delays. This pull request was opened well over 2 months ago, and has yet to receive either resolution or a reason for rejection.

Given your handling of this issue, you've demonstrated a great degree of irresponsibility and negligence for a package maintainer. 

To summarize where we stand:
  - All tests pass on my computer when run locally.
  - I cannot reproduce the build failure.
  - You refuse to merge because the CI build fails.
  - It's your responsibility to configure the CI server, OR advise me on how to fix it.
  - You have neither merged nor provided said advice.

I expect you to provide me with either advice on how to fix it, or alternatively resolve the issue yourself by the end of this week, otherwise I will consider this PR rejected.

**Comment by kolektiv** [comment]
Hi Varon,

Sorry this has taken much longer than I would like, you're right that it's
taken far longer than it should which is my fault. I'll get this looked at
ASAP and get back to you. Just to be clear, and making sure that the end
use is met - the main (only) goal is to have a NET35 version available as a
package?

Andrew

**Comment by varon** [comment]
This PR moves Aether to the F# project scaffold - https://github.com/fsprojects/ProjectScaffold, as a recommended standard for open F# projects.

A secondary goal is to add support for NET35, which is readily achievable on the new scaffold.

**Comment by kolektiv** [comment]
Presumably being on the scaffold project but not being NET35 compatible
would not be a goal though? I had assumed that the shift to project
scaffold was to support the NET35 requirement (while I don't mind going the
project scaffold route if it has significant pluses, if the goal is mainly
to support NET35 I think a lighter way to do so is possible).

**Comment by varon** [comment]
If I had to choose between the two, getting it on the project scaffold is more important.

You can see the advantages in the README for the scaffold project.

**Comment by kolektiv** [comment]
I've not used the fsprojects scaffold for other projects as a conscious choice (complexity, personal taste) and would only really want to adopt it if there was a specific requirement. I'm happy to release Aether as NET35 but I'm not sure that adopting the fsprojects scaffold just as "a good thing" is needed in that sense (the same build process as Aether is used for Freya, Chiron, Hekate, SemVer, without any issues at the moment). Would getting a NET35 build out soon (tomorrow) and following up with a scaffold review shortly after be OK for now? Presumably a NET35 build is required for another project?

**Comment by varon** [comment]
From my side, I'd personally like a NET35 build. I don't particularly mind how it gets done, as long as there's a NuGet package I can reference as a dependency.

My eventual goal for Aether is to get lenses (and generated lenses) included in [fsharp core](https://github.com/fsharp/fsharp), so my logic is that moving towards standards suggested by the [Recommended Guidelines for F# Projects, Packages and Namespaces ](https://fsharp.github.io/2014/09/19/fsharp-libraries.html) should eventually help with this.

Ultimately, all I can do is motivate the change; as you are the maintainer of this project, the decision on whether or not to use the scaffold is ultimately up to you. Your decision, whichever it might be, is something I'll have to live with.

Thanks for providing clear and prompt responses so far.

**Comment by kolektiv** [comment]
Hi Varon,

I'll investigate more on the scaffold change now, although I think it may be overkill for Aether. I've just pushed a 7.0 to NuGet which is NET35, and also updates the common lenses included to the lens_ naming convention (just FYI if you're using any!). Hopefully this makes Aether more generally useful for you.

Sorry it's been a slog with this - I've been pretty burnt out and snowed under lately. No excuse I know, but apologies, not the kind of process I normally try and run.

**Comment by varon** [comment]
Given Aether's progression since this was submitted, I think we can safely drop this PR at this stage, unless you feel extremely inclined towards archaeology.

**Comment by kolektiv** [comment]
Hah, fair enough - hopefully Aether and the changes have worked for you? I've been keen to maintain the net35 support for those who need it! I hope the later Aether iterations have made things neater for people too...

**Comment by varon** [comment]
At present I'm no longer using .Net35 for any of my projects. It may turn out that I need it later, so keeping support for it is appreciated.

**Comment by kolektiv** [comment]
Cool. I'll be keeping things as low on requirements as possible, so it'll be staying until there's a good reason to remove it!

**Pull request closed without merging**
