### PR TITLE
Include source files in package for Fable support

### PR DESCRIPTION
**Pull request by stroborobo**
Hey there!

The Fable FAQ asks to add the source files to the NuGet package: https://fable.io/faq/#library-authors
Not sure how to test this properly, tbh, but the library itself does work fine if copied into a Fable project.

### CODE REVIEW

**Comment by stroborobo** [comment]
In case you're not familiar with Fable, here's a little application for testing this:  
https://github.com/stroborobo/FableAetherTest

If you remove the Aether.fs from the fsproj, the build fails with messages like "Cannot resolve Aether [...]"

**Comment by et1975** [comment]
I already publish a [build of Aether for Fable](/et1975/fable-aether), if you need some changes maybe PR my repo instead?

**Comment by stroborobo** [comment]
@et1975 Oh nice! Would there be an advantage in not having this in the original package?

**Comment by panesofglass** [comment]
@et1975 should we merge the two together? I'm happy to make it happen.

**Comment by et1975** [comment]
Technically, Aether fitting into a single file doesn't need a package, one could (and some people do) import it at the source level directly into their app.

Reasons to keep Fable build in a separate project, all kinda weak:

- Fable has changed its lib packaging requirements twice in my memory (some packages are still only on npm)
- Due to JS runtime Fable's generics are non-reified and that leads to occasional hacks in the code (so it may diverge). 
- Tests of generated JS code.

If you want I can transfer the repo to xyncro, or whatever... I'm OK with whatever you have in mind @panesofglass.

**Comment by stroborobo** [comment]
I'll just close this then, not a significant change anyways.

**Pull request closed without merging**
